// constants.js

const SHEET_NAME = "Nations"; // This will not be used in Node.js, but kept for reference
const PURCHASE_PRICE = 1500; // Original was 2000 in HTML, but 1500 in JS. Using 1500 from JS.

// ユニットコスト (お金)
const INFANTRY_COST = 30;
const TANK_COST = 70;
const MECHANIZED_INFANTRY_COST = 50;
const BOMBER_COST = 90;
const MISSILE_COST = 10000;

// ユニットコスト (資源)
const INFANTRY_OIL_COST = 1;
const INFANTRY_IRON_COST = 2;

const TANK_OIL_COST = 3;
const TANK_IRON_COST = 5;

const MECHANIZED_INFANTRY_OIL_COST = 2;
const MECHANIZED_INFANTRY_IRON_COST = 3;

const BOMBER_OIL_COST = 5;
const BOMBER_IRON_COST = 7;

const MISSILE_OIL_COST = 50;
const MISSILE_IRON_COST = 100;

// 戦闘力
const INFANTRY_POWER = 2;
const TANK_POWER = 7;
const MECHANIZED_INFANTRY_POWER = 4;

// 爆撃によるユニットの破壊率
const BOMBER_INFANTRY_DESTRUCTION_RATE = 0.4;
const BOMBER_TANK_DESTRUCTION_RATE = 0.3;
const BOMBER_MECH_DESTRUCTION_RATE = 0.3;

// 領土ごとの資源生産量 (GeoJSONのprops.nameを使用)
const TERRITORY_RESOURCES = {
  "Saudi Arabia": { oil: 50, iron: 5 },
  Russia: { oil: 40, iron: 10 },
  "United States": { oil: 30, iron: 15 },
  Venezuela: { oil: 60, iron: 2 },
  Canada: { oil: 20, iron: 20 },
  Nigeria: { oil: 35, iron: 3 },
  Iraq: { oil: 45, iron: 4 },
  Iran: { oil: 40, iron: 5 },
  Mexico: { oil: 15, iron: 8 },
  Norway: { oil: 10, iron: 5 },
  Australia: { oil: 5, iron: 50 },
  Brazil: { oil: 3, iron: 45 },
  China: { oil: 10, iron: 30 },
  India: { oil: 8, iron: 35 },
  "South Africa": { oil: 2, iron: 25 },
  Sweden: { oil: 1, iron: 15 },
  Ukraine: { oil: 2, iron: 18 },
  Germany: { oil: 5, iron: 10 },
  "United Kingdom": { oil: 5, iron: 8 },
  France: { oil: 3, iron: 7 },
  Japan: { oil: 1, iron: 2 },
  "South Korea": { oil: 1, iron: 3 },
  Egypt: { oil: 7, iron: 6 },
  Argentina: { oil: 4, iron: 9 },
  Italy: { oil: 2, iron: 4 },
  Spain: { oil: 2, iron: 5 },
  Poland: { oil: 3, iron: 6 },
  Turkey: { oil: 6, iron: 12 },
  Indonesia: { oil: 10, iron: 10 },
  Kazakhstan: { oil: 15, iron: 10 },
  Algeria: { oil: 20, iron: 5 },
  Libya: { oil: 25, iron: 2 },
  Vietnam: { oil: 5, iron: 5 },
  Thailand: { oil: 4, iron: 4 },
  Malaysia: { oil: 8, iron: 6 },
  Philippines: { oil: 3, iron: 7 },
  Colombia: { oil: 12, iron: 8 },
  Peru: { oil: 6, iron: 10 },
  Chile: { oil: 3, iron: 12 },
  "North Korea": { oil: 1, iron: 10 },
  Cuba: { oil: 1, iron: 3 },
  Greece: { oil: 1, iron: 2 },
  Austria: { oil: 1, iron: 2 },
  Belgium: { oil: 1, iron: 2 },
  Netherlands: { oil: 1, iron: 2 },
  Switzerland: { oil: 0, iron: 1 },
  Portugal: { oil: 1, iron: 3 },
  Finland: { oil: 1, iron: 5 },
  Singapore: { oil: 0, iron: 0 },
  "New Zealand": { oil: 1, iron: 1 },
  "Czech Republic": { oil: 1, iron: 3 },
  Slovakia: { oil: 1, iron: 2 },
  Hungary: { oil: 1, iron: 2 },
  Romania: { oil: 4, iron: 6 },
  Bulgaria: { oil: 1, iron: 3 },
  Serbia: { oil: 1, iron: 4 },
  Croatia: { oil: 1, iron: 2 },
  "Bosnia and Herzegovina": { oil: 0, iron: 2 },
  Albania: { oil: 1, iron: 2 },
  "North Macedonia": { oil: 0, iron: 1 },
  Montenegro: { oil: 0, iron: 1 },
  Kosovo: { oil: 0, iron: 1 },
  Moldova: { oil: 0, iron: 0 },
  Belarus: { oil: 1, iron: 5 },
  Lithuania: { oil: 0, iron: 1 },
  Latvia: { oil: 0, iron: 1 },
  Estonia: { oil: 0, iron: 1 },
  Georgia: { oil: 1, iron: 2 },
  Armenia: { oil: 0, iron: 1 },
  Azerbaijan: { oil: 15, iron: 3 },
  Turkmenistan: { oil: 20, iron: 2 },
  Uzbekistan: { oil: 8, iron: 8 },
  Kyrgyzstan: { oil: 1, iron: 2 },
  Tajikistan: { oil: 1, iron: 2 },
  Afghanistan: { oil: 1, iron: 5 },
  Pakistan: { oil: 5, iron: 10 },
  Bangladesh: { oil: 1, iron: 1 },
  Nepal: { oil: 0, iron: 1 },
  Bhutan: { oil: 0, iron: 0 },
  "Sri Lanka": { oil: 1, iron: 1 },
  Myanmar: { oil: 7, iron: 9 },
  Laos: { oil: 1, iron: 3 },
  Cambodia: { oil: 1, iron: 2 },
  "Timor-Leste": { oil: 5, iron: 0 },
  "Papua New Guinea": { oil: 5, iron: 8 },
  Fiji: { oil: 0, iron: 0 },
  "Solomon Islands": { oil: 0, iron: 1 },
  Vanuatu: { oil: 0, iron: 0 },
  "New Caledonia": { oil: 0, iron: 5 },
  Somalia: { oil: 1, iron: 2 },
  Ethiopia: { oil: 1, iron: 3 },
  Kenya: { oil: 2, iron: 4 },
  Tanzania: { oil: 2, iron: 5 },
  Uganda: { oil: 3, iron: 2 },
  "Dem. Rep. Congo": { oil: 5, iron: 15 },
  Angola: { oil: 15, iron: 7 },
  Zambia: { oil: 1, iron: 8 },
  Zimbabwe: { oil: 1, iron: 6 },
  Mozambique: { oil: 2, iron: 7 },
  Madagascar: { oil: 1, iron: 3 },
  "Côte d'Ivoire": { oil: 3, iron: 4 },
  Ghana: { oil: 5, iron: 6 },
  Cameroon: { oil: 4, iron: 5 },
  Gabon: { oil: 10, iron: 2 },
  "Republic of the Congo": { oil: 8, iron: 1 },
  "Equatorial Guinea": { oil: 7, iron: 1 },
  Sudan: { oil: 10, iron: 5 },
  "South Sudan": { oil: 12, iron: 1 },
  Mauritania: { oil: 1, iron: 10 },
  Mali: { oil: 1, iron: 4 },
  Niger: { oil: 5, iron: 2 },
  "Burkina Faso": { oil: 1, iron: 3 },
  Benin: { oil: 1, iron: 1 },
  Togo: { oil: 1, iron: 1 },
  Guinea: { oil: 1, iron: 7 },
  "Sierra Leone": { oil: 1, iron: 3 },
  Liberia: { oil: 1, iron: 5 },
  Senegal: { oil: 2, iron: 3 },
  Gambia: { oil: 0, iron: 0 },
  "Guinea-Bissau": { oil: 0, iron: 0 },
  "Cape Verde": { oil: 0, iron: 0 },
  Iceland: { oil: 0, iron: 0 },
  Ireland: { oil: 0, iron: 1 },
  Denmark: { oil: 1, iron: 1 },
  Cyprus: { oil: 0, iron: 0 },
  Malta: { oil: 0, iron: 0 },
  Tunisia: { oil: 3, iron: 2 },
  Morocco: { oil: 2, iron: 5 },
  "Western Sahara": { oil: 0, iron: 0 },
  "São Tomé and Príncipe": { oil: 0, iron: 0 },
  Comoros: { oil: 0, iron: 0 },
  Seychelles: { oil: 0, iron: 0 },
  Mauritius: { oil: 0, iron: 0 },
  Bahamas: { oil: 0, iron: 0 },
  Jamaica: { oil: 0, iron: 1 },
  Haiti: { oil: 0, iron: 0 },
  "Dominican Republic": { oil: 0, iron: 1 },
  "Puerto Rico": { oil: 0, iron: 0 },
  "Trinidad and Tobago": { oil: 5, iron: 0 },
  Barbados: { oil: 0, iron: 0 },
  Grenada: { oil: 0, iron: 0 },
  "Saint Lucia": { oil: 0, iron: 0 },
  "Saint Vincent and the Grenadines": { oil: 0, iron: 0 },
  "Antigua and Barbuda": { oil: 0, iron: 0 },
  "Saint Kitts and Nevis": { oil: 0, iron: 0 },
  Dominica: { oil: 0, iron: 0 },
  Belize: { oil: 0, iron: 0 },
  Guatemala: { oil: 1, iron: 2 },
  "El Salvador": { oil: 0, iron: 0 },
  Honduras: { oil: 1, iron: 1 },
  Nicaragua: { oil: 1, iron: 1 },
  "Costa Rica": { oil: 0, iron: 0 },
  Panama: { oil: 0, iron: 1 },
  Guyana: { oil: 10, iron: 5 },
  Suriname: { oil: 5, iron: 3 },
  "French Guiana": { oil: 0, iron: 0 },
  Ecuador: { oil: 15, iron: 3 },
  Bolivia: { oil: 5, iron: 10 },
  Paraguay: { oil: 0, iron: 1 },
  Uruguay: { oil: 0, iron: 1 },
  "San Marino": { oil: 0, iron: 0 },
  "Vatican City": { oil: 0, iron: 0 },
  Monaco: { oil: 0, iron: 0 },
  Andorra: { oil: 0, iron: 0 },
  Liechtenstein: { oil: 0, iron: 0 },
  Luxembourg: { oil: 0, iron: 1 },
  Slovenia: { oil: 0, iron: 1 },
  Kuwait: { oil: 30, iron: 1 },
  Qatar: { oil: 25, iron: 1 },
  "United Arab Emirates": { oil: 28, iron: 1 },
  Oman: { oil: 15, iron: 2 },
  Yemen: { oil: 5, iron: 3 },
  Jordan: { oil: 1, iron: 2 },
  Lebanon: { oil: 0, iron: 0 },
  Syria: { oil: 5, iron: 4 },
  Israel: { oil: 0, iron: 0 },
  "West Bank": { oil: 0, iron: 0 },
};

const NATIONAL_FOCUSES = {
  industrial_expansion: {
    name: "産業拡大",
    description: "鉄と石油の生産量を増加させ、経済を活性化します。",
    costTurns: 5,
    effects: {
      ironProductionBonus: 0.2,
      oilProductionBonus: 0.2,
      moneyProductionBonus: 0.1,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  military_modernization: {
    name: "軍事近代化",
    description: "歩兵と戦車の戦闘力を向上させ、軍事力を強化します。",
    costTurns: 7,
    effects: {
      infantryPowerBonus: 1,
      tankPowerBonus: 1,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  Tourism_industry_development: {
    name: "観光業発展",
    description: "観光業が発展し、人口とお金増加率が向上します。",
    costTurns: 9,
    effects: {
      populationGrowthBonus: 0.002,
      moneyProductionBonus: 0.02,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  population_growth_initiative: {
    name: "人口増加計画",
    description: "人口増加率を向上させ、国力を増大させます。",
    costTurns: 4,
    effects: {
      populationGrowthBonus: 0.002,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  missile_development: {
    name: "ミサイル開発",
    description: "ミサイルの生産コストを削減します。",
    costTurns: 6,
    effects: {
      missileCostReduction: 0.1,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  mechanized_warfare_doctrine: {
    name: "機械化戦術ドクトリン",
    description: "機械化歩兵と戦車の戦闘力をさらに向上させます。",
    costTurns: 8,
    effects: {
      mechanizedInfantryPowerBonus: 2,
      tankPowerBonus: 0.5,
    },
    prerequisites: ["military_modernization"],
    exclusiveWith: [],
  },
  national_fortification_program: {
    name: "国家要塞化計画",
    description: "防衛ボーナスを強化し、領土の防御力を高めます。",
    costTurns: 6,
    effects: {
      defenseBonusIncrease: 0.1,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
  air_force_logistics: {
    name: "空軍兵站最適化",
    description: "爆撃機の生産コストを削減します。",
    costTurns: 5,
    effects: {
      bomberCostReduction: 0.1,
    },
    prerequisites: [],
    exclusiveWith: [],
  },
};

const ALLIANCES_SHEET_NAME = "Alliances"; // Not directly used as sheet name, but as identifier

module.exports = {
  SHEET_NAME,
  PURCHASE_PRICE,
  INFANTRY_COST,
  TANK_COST,
  MECHANIZED_INFANTRY_COST,
  BOMBER_COST,
  MISSILE_COST,
  INFANTRY_OIL_COST,
  INFANTRY_IRON_COST,
  TANK_OIL_COST,
  TANK_IRON_COST,
  MECHANIZED_INFANTRY_OIL_COST,
  MECHANIZED_INFANTRY_IRON_COST,
  BOMBER_OIL_COST,
  BOMBER_IRON_COST,
  MISSILE_OIL_COST,
  MISSILE_IRON_COST,
  INFANTRY_POWER,
  TANK_POWER,
  MECHANIZED_INFANTRY_POWER,
  BOMBER_INFANTRY_DESTRUCTION_RATE,
  BOMBER_TANK_DESTRUCTION_RATE,
  BOMBER_MECH_DESTRUCTION_RATE,
  TERRITORY_RESOURCES,
  NATIONAL_FOCUSES,
  ALLIANCES_SHEET_NAME,
};
